### ISSUE TITLE
recipe won't run - LWRP not found

### ISSUE THREAD

**Issue by danryu** [elliotkendallUCSF/chef-opendj#1]
For the life of me I can't find out why this recipe won't run. I've followed instructions in README. It seems that it can't find the LWRP but after checking on the target node, the whole cookbook is sitting in the cache, providers directory and all.

Any idea why this is failing?

NameError: Cannot find a resource for opendj_postinstallconfig on centos version 6.3
/usr/lib64/ruby/gems/1.8/gems/chef-10.24.0/bin/../lib/chef/resource_platform_map.rb:126:in `get'
/usr/lib64/ruby/gems/1.8/gems/chef-10.24.0/bin/../lib/chef/resource.rb:859:in`resource_for_platform'
/usr/lib64/ruby/gems/1.8/gems/chef-10.24.0/bin/../lib/chef/resource.rb:876:in `resource_for_node'
/usr/lib64/ruby/gems/1.8/gems/chef-10.24.0/bin/../lib/chef/mixin/recipe_definition_dsl_core.rb:58:in`method_missing'
/var/chef/cache/cookbooks/chef-opendj/recipes/default.rb:31:in `from_file'

**Comment by elliotkendallUCSF** [comment]
That's odd, especially since this was developed on CentOS 6.3. Can you send me a (sanitized) node/role config so that I can try to replicate your problem?

**Comment by danryu** [comment]
Sure - what in particular do you want to see?
I have no roles/environments defined. I'm installing (via Cloudify) onto a 4Gb Rackspace CentOS6.3 VM with a single recipe in the run-list (recipe[chef-opendj::default]).

**Comment by elliotkendallUCSF** [comment]
Just the attributes you have defined for that node, then. Are you running chef-solo? How are you installing chef on the vm?

**Comment by danryu** [comment]
I have not defined any attributes at all for the node. I wanted to do a completely "vanilla" installation to see what the result was. 
I'm not running chef-solo, no. I'm using a cloud deployment tool called Cloudify, which issues wrapper commands to first install chef-client and then run the selected recipe (chef-opendj::default) in this case.
Chef version is 10.24.0.

**Comment by danryu** [comment]
I uploaded the failed_run_data.json.
Is there anything else I can provide? I'm spending way too much time trying to get this recipe to run......

https://gist.github.com/dan77g/5339032

**Comment by elliotkendallUCSF** [comment]
I suspect this is something to do with cloudify. I'd probably have to set that up myself to replicate the problem. You might also try installing chef the usual way and see if that works any better.

I will take a deeper look at this at some point, but supporting chef cookbooks is mostly an as-time-permits kind of thing. If you need this to work ASAP, you may want to look elsewhere.

**Comment by danryu** [comment]
I had a feeling that it was something really stupid - and finally I saw that the cookbook directory was named "chef-opendj" rather than "opendj", and that was why the provider auto-naming wasn't working ....
My apologies for the confusion - and thanks for the responses.

Now the recipe is falling over at this point:

NoMethodError
undefined method `[]' for nil:NilClass

Cookbook Trace:
  /var/chef/cache/cookbooks/opendj/recipes/default.rb:42:in `from_file'

Relevant File Content:
/var/chef/cache/cookbooks/opendj/recipes/default.rb:

``` ruby
 41:  
 42>> template "#{node['tomcat']['config_dir']}/Catalina/localhost/dsml.xml" do
 43:    source "dsml.xml.erb"
 44:    mode 0644
 45:  end
```

I hadn't spotted this before. Why is tomcat implied as a dependency? My understanding was that OpenDJ installs standalone - as outlined at http://opendj.forgerock.org/doc/install-guide/index.html.
(There's no mention of tomcat integration there.)

Am I missing something (again) ?

**Comment by danryu** [comment]
It's for the DSML gateway isn't it? I'm still catching up with this stuff. I guess I'll include the tomcat recipe at the start of default.rb?

**Comment by elliotkendallUCSF** [comment]
I just pushed a commit that will let you disable use of the DSML gateway. It was a good idea anyway, and it might save you some time. Just set 

node['opendj']['dsml_enabled'] = false

in the attribute config for your node. I also wouldn't be surprised if there were other attributes you need to set for the recipe to work correctly, but you'll find that out shortly :)

**Comment by danryu** [comment]
Thanks for the update.

I have indeed fallen over again at this point:
NoMethodError: opendj_postinstallconfig[default](opendj::default line 34) had an error: NoMethodError: undefined method `each' for nil:NilClass
/var/chef/cache/cookbooks/opendj/providers/postinstallconfig.rb:106:in`class_from_file'

Which suggests I've got something to set with "indexes" ... but that will have to wait until I've learnt a bit more about OpenDJ ....

**Comment by elliotkendallUCSF** [comment]
For what it's worth, I just pushed a commit that should let the recipe run without the indexes attribute being set. I doubt opendj will be very useful without any indexes defined, though.

**Comment by danryu** [comment]
Thanks Elliott.
By the way, I am writing chefspec unit tests for this opendj recipe, and I've hit an issue with the line 74 of default.rb, where you do

``` ruby
    results = Chef::Search::Query.new.search(:node, node["opendj"]["replication"]["host_search"]).first.compact
```

That's going to return:

``` ruby
[node[my_node_1], node[my_node_2], node[my_node_3]]
```

Then you're calling .first, which will return:

``` ruby
node[my_node_1] # a node object
```

and then you're calling .compact on that:

``` ruby
NoMethodError
```

Since Array#compact is an array method, not a node method.
Similarly, if your search returns an empty array:

``` ruby
search(:node, node['opendj']['replication']['host_search']) #=> []
```

And you call .first.compact:

``` ruby
[].first #=> nil
nil.compact #=> NoMethodError
```

Do we need to re-factor this a bit?
If you like, I can submit a patch when I have something working.

**Comment by elliotkendallUCSF** [comment]
Huh. Wonder why it works, then. Anyway, I've pushed a commit that should avoid the problem.
